### ISSUE TITLE
Error: No 'lines' defined

### ISSUE THREAD

**Issue by CieNTi** [samchrisinger/markdown-it-toc#2]
I just installed and tried toc plugin but i get this error:
```off
/home/doc/md2pdf/mdit.test/node_modules/markdown-it-toc/index.js:80
           var anchor = makeSafe(label.content) + '_' + label.lines[0];
                                                                   ^
TypeError: Cannot read property '0' of undefined
```

If I put a simple `console.log( tokens )`, i get (only affected part shown, at first heading):
```js
(...)
  { type: 'inline',
    tag: '',
    attrs: null,
    map: [ 0, 1 ],
    nesting: 0,
    level: 1,
    children: [ [Object] ],
    content: 'Ejercicios de Antenas, Radiopropagación y Comunicaciones Móviles',
    markup: '',
    info: '',
    meta: null,
    block: true,
    hidden: false },
(...)
```
Switching now to `console.log( label )` I get:
```js
{ type: 'inline',
  tag: '',
  attrs: null,
  map: [ 0, 1 ],
  nesting: 0,
  level: 1,
  children:
   [ { type: 'text',
       tag: '',
       attrs: null,
       map: null,
       nesting: 0,
       level: 0,
       children: null,
       content: 'Ejercicios de Antenas, Radiopropagación y Comunicaciones Móviles',
       markup: '',
       info: '',
       meta: null,
       block: false,
       hidden: false } ],
  content: 'Ejercicios de Antenas, Radiopropagación y Comunicaciones Móviles',
  markup: '',
  info: '',
  meta: null,
  block: true,
  hidden: false }
```

If I search on your code, `lines` is used only twice ... but no more reference is found

What's wrong? If it's my fault, where?

Thanks in advance,
CieNTi

**Comment by samchrisinger** [comment]
@CieNTi, thank you for catching this. 

I'm having a hard time duplicating this. Would you mind copy/pasting the text being parsed that creates this error?

**Comment by CieNTi** [comment]
Sure!

## Source:
```markdown
Ejercicios de Antenas, Radiopropagación y Comunicaciones Móviles
================================================================

@[toc](Titulo del toc)

[newPage]

## Problema 1

### Apartado -a-

El campo total es el producido por un array de dos dipolos al que le añadimos el efecto del plano conductor aplicando imágenes. En la siguiente figura se interpreta el doble dipolo, el plano conductor y semitransparentes, las imágenes del sistema.

![Simulación del doble dipolo, plano conductor e imágenes](https://lh3.googleusercontent.com/rl7vp786gPeK9N3DwlsLwxFRKjU-McJljpcAfLWt7A=s400 "Simulación del doble dipolo, plano conductor e imágenes")

Orientamos los dipolos según el eje $z$ y elegimos el eje $y$ como eje del array, obteniendo el campo producido por un dipolo de $\frac{\lambda}{2}$ aislado:
$$\begin{equation}
\vec{E}_{dipolo_{\frac{\lambda}{2}}} = j60I \cdot \frac{e^{−jkr}}{r} \cdot \frac{cos\left(\frac{π}{2}cos\theta\right)}{sen\theta} \cdot \hat{\theta}
\end{equation}$$

[newPage]

El campo total es:
$$\begin{equation}
\vec{E}_{antena} = \vec{E}_{dipolo_{\frac{\lambda}{2}}} \cdot FA_{1}(\psi_{y}) \cdot FA2 (\psi_{x})
\end{equation}$$

Recordamos y tomamos en consideración que:

1. El array de dipolos están separados $\frac{\lambda}{2}$ entre si
2. Están contenidos en el plano $YZ$
3. El eje $X $ pasa perpendicularmente por el centro del sistema
4. El plano conductor infinito está a $\frac{\lambda}{4}$ del origen y es paralelo a $YZ$

Esto lleva a deducir que *el campo debe salir proyectado desde el sistema hacia el semieje positivo de $X $, tomándose este como eje de superficie de revolución del volumen creado por el campo.*

[newPage]
### Apartado -d-

Además se observa que la distancia entre los dipolos del array es la misma que la que hay entre un dipolo y su imagen, por lo tanto $Z_d = Z_{11} - Z_{14}$. La autoimpedancia se puede calcular sabiendo que es aproximadamente la impedancia mutua cuando la separaci$

[newPage]
### Apartado -e-

$$\begin{equation}
\left|l_{ef\ max}\right| = \frac{\left|N_{max}\right|}{\left|I_{in}\right|} = \frac{\frac{\lambda}{\pi}\left|I_d\right| \cdot 2 \cdot 2}{\left|I_{in}\right|} = 2.5\frac{\lambda}{\pi}
\end{equation}$$

[newPage]

## Problema 2

Al tratarse en cada apartado con los 3 entornos el problema se estructura a la inversa, agrupando apartados por entorno a fin de hacer mas lineal la lectura de resultados.
<hr />

### Entorno rural: Densidad de tráfico $10\frac{ab}{km^2}$ y $n = 3.2$

#### **Apartado -a: Mínimo valor de J (número de células por cluster)**

> Como J tiene que ser un numero rómbico debemos usar el mayor más próximo $J = 16$ para $\left(i, j\right) = \left(4, 0\right)$

[newPage]
```

## Results:
```off
doc@pulsar:~/md2pdf/mdit.test$ node app.js

/home/doc/md2pdf/mdit.test/node_modules/markdown-it-toc/index.js:79
            var anchor = makeSafe(label.content) + '_' + label.lines[0];
                                                                    ^
TypeError: Cannot read property '0' of undefined
    at Object.md.renderer.rules.heading_open (/home/doc/md2pdf/mdit.test/node_modules/markdown-it-toc/index.js:79:69)
    at Renderer.render (/home/doc/md2pdf/mdit.test/node_modules/markdown-it/lib/renderer.js:291:38)
    at MarkdownIt.render (/home/doc/md2pdf/mdit.test/node_modules/markdown-it/lib/index.js:502:24)
    at /home/doc/md2pdf/mdit.test/app.js:83:20
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

And it's happening where the first post information :)

Thanks in advance,
CieNTi

**Comment by CieNTi** [comment]
Hello?

**Comment by samchrisinger** [comment]
@CieNTi, sorry for my slowness.

I haven't had a lot of time to investigate this in depth, but can say with certainty that this plugin was developed against markdown-it@3.0.5. ATM there is no plan to support versions 4+.

If markdown-it@4.0.x is not a requirement for your work, you might consider downgrading.
